flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-0.11.2.0
- aeson-compat-0.3.5.1
- aeson-pretty-0.8.1
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- appar-0.1.4
- async-2.1.0
- attoparsec-0.13.0.2
- auto-update-0.1.4
- base-compat-0.9.1
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.2
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- bytestring-conversion-0.3.1
- bytestring-lexing-0.5.0.2
- case-insensitive-1.2.0.7
- cmdargs-0.10.14
- cookie-0.4.2.1
- cryptonite-0.17
- data-default-class-0.1.2.0
- dlist-0.8
- double-conversion-2.0.1.0
- easy-file-0.2.1
- exceptions-0.8.3
- fail-4.9.0.0
- fast-logger-2.4.6
- file-embed-0.0.10
- hashable-1.2.4.0
- hedis-0.9.1
- hex-0.1.2
- http-api-data-0.2.3
- http-date-0.0.6.1
- http-media-0.6.4
- http-types-0.9.1
- http2-1.6.1
- iproute-1.7.0
- lifted-base-0.2.3.8
- memory-0.13
- mime-types-0.1.0.7
- mmorph-1.0.6
- monad-control-1.0.1.0
- mtl-2.2.1
- nats-1.1.1
- network-2.6.2.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.12.1.0
- parsec-3.1.11
- primitive-0.6.1.0
- psqueues-0.2.2.1
- random-1.1
- resource-pool-0.2.3.2
- resourcet-1.1.7.4
- safe-0.3.9
- scanner-0.2
- scientific-0.3.4.9
- semigroups-0.18.2
- servant-0.8
- servant-server-0.8
- simple-sendfile-0.2.25
- split-0.2.3.1
- stm-2.4.4.1
- streaming-commons-0.1.15.5
- string-conversions-0.4
- stringsearch-0.3.6.6
- syb-0.6
- system-filepath-0.4.13.4
- tagged-0.8.5
- text-1.2.2.1
- time-locale-compat-0.1.1.3
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.2.0
- unix-time-0.3.6
- unordered-containers-0.2.7.1
- utf8-string-1.0.1.1
- vault-0.3.0.6
- vector-0.11.0.0
- void-0.7.1
- wai-3.2.1.1
- wai-app-static-3.1.5
- wai-extra-3.0.16.1
- wai-logger-2.3.0
- warp-3.2.7
- word8-0.1.2
- zlib-0.6.1.1
resolver: ghc-8.0.1
