flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.3.1.1
- QuickCheck-2.8.2
- ansi-terminal-0.6.2.3
- async-2.1.0
- checkers-0.4.4
- hspec-2.2.3
- hspec-core-2.2.3
- hspec-discover-2.2.3
- hspec-expectations-0.7.2
- primitive-0.6.1.0
- quickcheck-io-0.1.3
- random-1.1
- setenv-0.1.1.3
- stm-2.4.4.1
- tf-random-0.5
resolver: ghc-8.0.1
